#!/bin/bash
#*****************************************************************
# Copyright (c) 2013 The 6Th Column Project
# All rights reserved.
#*****************************************************************
#
#  Organization: A Couple of Guys That Need A Life
#   Directorate: Computation
#    Department: Computing Applications and Research
#       Program: Tom Foolery
#       Project: BASH-FOO
# First Authors: Gavin M. Bell (gavin@llnl.gov) &
#                Charles Doutriaux (doutriaux1@llnl.gov)
#
#   Description:
#   A clean and easy way to setup your bash environment that is hassle free.
#   We use lots of different machines... it makes it less painful
#
#   Sets up dot bash files in your home directory
#
#*****************************************************************

#TODO - implement revert_homedir function
#TODO - write arg code to trigger revert if necessary

DEBUG=0
DRY_RUN=0

homedir=${homedir:-${HOME:?"HOME environment var must be set!!!!"}}

programs_to_check_for=(fortune uname uptime)

quick_checks() {
    local oops_count=0
    for program in ${programs_to_check_for[@]}; do
        ${program} >& /dev/null
        if [ $? != 0 ]; then
            ((oops_count++))
            echo "Couldn't find [${program}]"
        fi
    done
    if ((oops_count > 0)); then
        echo "Warning: You may want to install the missing programs for optimum use..."
        if uname -a | grep -q Darwin; then
            echo "  MacPorts: https://www.macports.org/install.php"
            echo "> port install <program>"
        else
            echo "  Please install the missing program(s) for optimum use (yum, apt-get, rpm, etc..)"
        fi
    fi
}

# Utility "private" method
_readlinkf() {
    # This is a portable implementation of GNU's "readlink -f" in
    # bash/zsh, following symlinks recursively until they end in a
    # file, and will print the full dereferenced path of the specified
    # file even if the file isn't a symlink.
    #
    # Loop detection exists, but only as an abort after passing a
    # maximum length.

    local start_dir=$(pwd)
    local file=${1}
    cd $(dirname ${file})
    file=$(basename ${file})

    # Iterate down symlinks.  If we exceed a maximum number symlinks, assume that
    # we're looped and die horribly.
    local maxlinks=20
    local count=0
    local current_dir
    while [ -L "${file}" ] ; do
        file=$(readlink ${file})
        cd $(dirname ${file})
        file=$(basename ${file})
        ((count++))
        if (( count > maxlinks )) ; then
            current_dir=$(pwd -P)
            echo "CRITICAL FAILURE[4]: symlink loop detected on ${current_dir}/${file}"
            cd ${start_dir}
            exit ${count}
        fi
    done
    current_dir=$(pwd -P)
    echo "${current_dir}/${file}"
    cd ${start_dir}
}

setup_dot_bash_files() {
    [ ! -e .git ] && echo "Sorry this is not a git repo" && exit 1
    
    for dot_file in $(ls -a | grep bash); do
        echo -n "setting up $dot_file... "
        #check if the file exists already
        if [ "$(_readlinkf ${dot_file})" == "$(_readlinkf ${homedir}/${dot_file} | tail -n 1)" ]; then
            echo "[OK] (nothing to do already linked)"
        else
            ((DEBUG|DRY_RUN)) && echo "[ -e ${homedir}/${dot_file} ]  && mv -v ${homedir}/${dot_file}{,.bak}"
            ((! DRY_RUN)) && [ -e ${homedir}/${dot_file} ] && mv -v ${homedir}/${dot_file}{,.bak}
            ((DEBUG||DRY_RUN)) && echo "ln -s $(_readlinkf ${dot_file}) ${homedir}/${dot_file}"
            if ((! DRY_RUN)); then
                ln -s $(_readlinkf ${dot_file}) ${homedir}/${dot_file}
                [ $? != 0 ] && echo "ERROR: problem linking ${dot_file}" || echo " linked file... [OK] "
            fi
        fi
    done
}

revert_homedir() {
    [ ! -e .git ] && echo "Sorry this is not a git repo" && exit 1
    echo " Revert Not Yet Implemented"
    return 0
}

_usage() {
    printf "
Usage:
  > setup
           --install - Runs the installation process [default]
           --revert  - Uninstalls the system [not yet implemented]
           --help|-h - Prints this help message
           --debug   - Runs in debug mode (more output)
           --dry-run - Will not perform operations but will print what would be done

"
    exit 0
}

main() {
    while [ -n "$1" ]; do
	case "$1" in
	    --install)
		shift
                INSTALL=1
		break
		;;
	    --revert)
                shift
                REVERT=1
		;;
	    --help|-h)
		_usage
		;;
            --debug)
                shift
                DEBUG=1
                ;;
            --dry-run)
                shift
                DRY_RUN=1
                ;;
	    *)
		break
	esac
    done

    ((DEBUG)) && echo "Debug mode on"
    ((DRY_RUN)) && echo "Dry run mode on"

    if ((REVERT)); then revert_homedir; exit $?; fi

    #Functions that peform the installtion....
    quick_checks && setup_dot_bash_files $@
}

main $@
